# Generated by Django 6.0.6 on 2026-06-26 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patient_blood_group_patient_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('lmp', models.DateField()),
                ('edd', models.DateField()),
                ('gestational_age_weeks', models.PositiveIntegerField()),
                ('gravida', models.PositiveIntegerField()),
                ('parity', models.PositiveIntegerField()),
                ('pregnancy_status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Delivered', 'Delivered'), ('Miscarriage', 'Miscarriage'), ('Stillbirth', 'Stillbirth'), ('Terminated', 'Terminated')], default='Ongoing', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='patients.patient')),
            ],
        ),
    ]
