# Generated by Django 6.0.6 on 2026-07-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_options_alter_patient_blood_group_and_more'),
        ('pregnancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregnancy',
            options={'ordering': ['-booking_date'], 'verbose_name': 'Pregnancy', 'verbose_name_plural': 'Pregnancies'},
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='edd',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='pregnancy_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Delivered', 'Delivered'), ('Miscarriage', 'Miscarriage'), ('Stillbirth', 'Stillbirth'), ('Terminated', 'Terminated')], db_index=True, default='Ongoing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['patient', 'pregnancy_status'], name='pregnancies_patient_bd96c4_idx'),
        ),
    ]
