# Generated by Django 6.0.6 on 2026-07-14 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patient_blood_group_patient_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GynecologyConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateField()),
                ('consultation_type', models.CharField(choices=[('Routine Checkup', 'Routine Checkup'), ('Menstrual Disorder', 'Menstrual Disorder'), ('Pelvic Pain', 'Pelvic Pain'), ('Vaginal Discharge', 'Vaginal Discharge'), ('Infertility', 'Infertility'), ('Fibroid Evaluation', 'Fibroid Evaluation'), ('Cervical Screening', 'Cervical Screening')], max_length=30)),
                ('presenting_complaint', models.TextField()),
                ('history', models.TextField(blank=True, default='')),
                ('examination_findings', models.TextField(blank=True, default='')),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('treatment', models.TextField(blank=True, default='')),
                ('follow_up_plan', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gynecology_consultations', to='patients.patient')),
            ],
        ),
    ]
