# Generated by Django 6.0.6 on 2026-07-23 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gynaecology', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gynecologyconsultation',
            options={'ordering': ['-consultation_date', '-id'], 'verbose_name': 'Gynaecology Consultation', 'verbose_name_plural': 'Gynaecology Consultations'},
        ),
    ]
