# Generated by Django 6.0.6 on 2026-07-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenatal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenatalvisit',
            name='fetal_movement_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='antenatalvisit',
            name='fundal_height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='antenatalvisit',
            name='next_appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antenatalvisit',
            name='pulse_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antenatalvisit',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='antenatalvisit',
            name='urine_glucose',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='antenatalvisit',
            name='urine_protein',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
