# Generated by Django 6.0.6 on 2026-07-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenatal', '0002_antenatalvisit_fetal_movement_present_and_more'),
        ('pregnancies', '0002_alter_pregnancy_options_alter_pregnancy_edd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antenatalvisit',
            options={'ordering': ['-visit_date'], 'verbose_name': 'Antenatal Visit', 'verbose_name_plural': 'Antenatal Visits'},
        ),
        migrations.AlterField(
            model_name='antenatalvisit',
            name='visit_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='antenatalvisit',
            index=models.Index(fields=['pregnancy', 'visit_date'], name='antenatal_a_pregnan_90f91d_idx'),
        ),
        migrations.AddConstraint(
            model_name='antenatalvisit',
            constraint=models.UniqueConstraint(fields=('pregnancy', 'visit_number'), name='unique_antenatal_visit_number'),
        ),
    ]
