# Generated by Django 6.0.6 on 2026-07-12 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostnatalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_number', models.PositiveIntegerField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=4)),
                ('pulse_rate', models.PositiveIntegerField()),
                ('lochia', models.CharField(blank=True, default='', max_length=50)),
                ('breastfeeding_status', models.CharField(choices=[('Exclusive', 'Exclusive'), ('Mixed', 'Mixed'), ('Not Breastfeeding', 'Not Breastfeeding')], max_length=30)),
                ('wound_healing', models.CharField(blank=True, default='', max_length=100)),
                ('baby_weight_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('feeding_well', models.BooleanField(default=True)),
                ('immunization_given', models.BooleanField(default=False)),
                ('family_planning_counseled', models.BooleanField(default=False)),
                ('next_appointment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postnatal_visits', to='deliveries.delivery')),
            ],
        ),
    ]
