# Generated by Django 6.0.6 on 2026-07-23 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postnatal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postnatalvisit',
            options={'ordering': ['-visit_date', '-id'], 'verbose_name': 'Postnatal Visit', 'verbose_name_plural': 'Postnatal Visits'},
        ),
    ]
