# Generated by Django 6.0.6 on 2026-07-12 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pregnancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_datetime', models.DateTimeField()),
                ('mode_of_delivery', models.CharField(choices=[('Vaginal', 'Vaginal'), ('Caesarean', 'Caesarean'), ('Assisted', 'Assisted')], max_length=20)),
                ('baby_sex', models.CharField(max_length=10)),
                ('birth_weight_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('apgar_1_min', models.PositiveIntegerField()),
                ('apgar_5_min', models.PositiveIntegerField()),
                ('baby_status', models.CharField(choices=[('Alive', 'Alive'), ('Stillbirth', 'Stillbirth')], default='Alive', max_length=20)),
                ('estimated_blood_loss_ml', models.PositiveIntegerField()),
                ('maternal_complications', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='pregnancies.pregnancy')),
            ],
        ),
    ]
