# Generated by Django 6.0.6 on 2026-07-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('pregnancies', '0002_alter_pregnancy_options_alter_pregnancy_edd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-delivery_datetime'], 'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='baby_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='baby_status',
            field=models.CharField(choices=[('Alive', 'Alive'), ('Stillbirth', 'Stillbirth')], db_index=True, default='Alive', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_datetime', 'baby_status'], name='deliveries__deliver_67eee0_idx'),
        ),
    ]
